# ProjectEuler 2
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

upper_lim = 4e6
fib = [1,2]

# Build Fibonacci Sequence
while True:
    if fib[len(fib)-2] + fib[len(fib)-1] >= upper_lim:
        break
    fib.append(fib[len(fib)-2] + fib[len(fib)-1])

even_sum = 0        
for n in fib:
    if n%2==0:
        even_sum+=n
        
print "Sum of all even Fibonacci numbers less than ", upper_lim, ": ", even_sum